title: Dr. Jekyll
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
just testing things out

# social links
twitter_username: michaelkgilson
github_username:  mkgilson

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
